name: Releaser

on:
  push:
    paths: ${{{ .github.languages | map(select(. == "Rust")) | if length == 0 then ["version.json"] else ["Cargo.toml"] end }}}
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: ipdxco/unified-github-workflows/.github/workflows/releaser.yml@${{{ .config.versions.uci // (.source.tag | sub("\\.[^\\.]+\\.[^\\.\\-\\+]+(?=\\-|\\+|$)"; "")) }}}
    with:
      sources: '${{{ .github.languages | map(select(. == "Rust")) | if length == 0 then ["version.json"] else ["Cargo.toml"] end }}}'
    secrets:
      UCI_GITHUB_TOKEN: ${{ secrets.UCI_GITHUB_TOKEN }}
