name: Update Go

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "List of repository names to deploy to"
        required: true
      version:
        description: "Go version to update to"
        required: true
      branch:
        description: "Branch to push to"
        required: false
        default: 'uci/update-go'
      dry-run:
        description: "Whether to run in dry run mode"
        required: false
        default: 'false'

jobs:
  update-go:
    uses: ./.github/workflows/process.yml
    secrets: inherit
    with:
      targets: ${{ github.event.inputs.targets }}
      branch: ${{ github.event.inputs.branch }}
      script: update-go.sh
      defaults: |
        versions:
          go: "${{ github.event.inputs.version }}"
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
